FROM maven
COPY ./ ./
RUN mvn clean package
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .
EXPOSE 6001
CMD ["java", "-javaagent:/opentelemetry-javaagent.jar", "-Dotel.resource.attributes=service.name=citizendemo.resourceapi", "-Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317", "-jar", "target/resourceapi-0.0.1-SNAPSHOT.jar"]