version: '3.4'
services:
  mongodb:
    image: mongo
    container_name: citizendemo-mongodatabase
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizendemo
      - MONGO_INITDB_ROOT_PASSWORD=citizendemo
    ports:
      - "27018:27017"
  citizendemo.resourceapi:
    image: citizendemo-resourceapi:latest
    container_name: citizendemo-resourceapi
    depends_on:
      - mongodb
    build:
      context: ../resourceapi
      dockerfile: dockerfile
    ports:
      - "6001:6001"
  citizendemo.citizenapi:
    image: citizendemo-citizenapi:latest
    container_name: citizendemo-citizenapi
    depends_on:
      - mongodb
      - citizendemo.resourceapi
    build:
      context: ../citizenapi
      dockerfile: dockerfile
    ports:
      - "5001:5001"
  citizendemo.loadgenerator:
    image: citizendemo-loadgenerator:latest
    container_name: citizendemo-loadgenerator
    depends_on:
      - citizendemo.citizenapi
    build:
      context: ../loadgenerator
      dockerfile: dockerfile
    ports:
      - "7001:7001"
  prometheus:
    image: prom/prometheus:latest
    container_name: citizendemo-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    container_name: citizendemo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=citizendemo
      - GF_SECURITY_ADMIN_PASSWORD=citizendemo
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards