spring.data.mongodb.database=CitizenDemo
spring.data.mongodb.uri=mongodb://citizendemo:citizendemo@host.docker.internal:27018
resourceAPI.url=http://host.docker.internal:6001/resources
server.port=5001
