spring.data.mongodb.database=CitizenDemo
spring.data.mongodb.uri=mongodb://citizendemo:citizendemo@host.docker.internal:27018
resourceAPI.url=http://host.docker.internal:6001/resources
server.port=5001
management.endpoints.web.exposure.include=prometheus
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics
metrics.tags.application: ${spring.application.name}
