server.port=7001
citizenAPI.url=http://host.docker.internal:5001/citizens
management.endpoints.web.exposure.include=prometheus
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics
metrics.tags.application: ${spring.application.name}